# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/EMDatasets',
                'doc_host': 'https://ECLIPSE-Lab.github.io',
                'git_url': 'https://github.com/ECLIPSE-Lab/EMDatasets',
                'lib_path': 'EMDatasets'},
  'syms': {'EMDatasets.core': {'EMDatasets.core.foo': ('core.html#foo', 'EMDatasets/core.py')}}}